# Description

Provide a summary of this change and the relevant motivation and context for why.  This description will be used in the changelog and release notes so write a well articulated description and don't include too much technical jargon.

## Source

Provide links to the projects, issues or discussions of this issue.

## Detail

Provide the technical details of the most critical and risky updates or changes that were made, including things related to the configuration, build, dependencies or reprecated or removed code, as well as anything else that may be important to note.

## Breaking Changes

Specify whether or not this update contains breaking changes and if so provide detail on what those breaking changes are and what exactly it breaks.

[ ] This update contains breaking changes.

## Checklist

- [ ] I have performed a self-review of my code and to the best of my knowledge everything should be working.
- [ ] I have tested my code and did quality assurance, as well as writing new tests where necessary.
- [ ] I have linted and formatted my code to be consistent with the existing codebase.
- [ ] I have pulled the latest changes before submitting this request and carefully resolved any merge conflicts.
- [ ] I have followed the [contributing](https://github.com/miamatriarx/miamatriarx/contributing.md) stipulations and my work contains a proper branch name and title and a linear commit history with properly named and formatted conventional commits.
- [ ] I understand that this contribution will fall under the [MIT](https://github.com/miamatriarx/miamatriarx/license.md) license and that I void all claims to any intellectual property or copyright.

@miamatriarx
