version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Build
          command: echo "Building"
  test:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Test
          command: echo "Testing"
  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Deploy
          command: echo "Deploying"
