name: Issue
description: Report a new issue
title: "Issue: "
labels: ["triage"]
assignees:
  - miamatriarx
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report an issue.  Before creating a new issue have a look at the existing [issues](https://github.com/miamatriarx/miamatriarx/issues) to make sure you don't create a duplicate issue, otherwise rather contribute to the existing issue.  Also only use this template if your issue is not related to a feature request, an improvement or a bug, otherwise use the relevant templates for those.
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: What is the issue?
      placeholder: Provide detail about your issue.
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Additional Information
      description: Do you have any additional information?
      placeholder: Provide any additional information relevant to your issue.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we contact you if we need more information or if we'd like to discuss it?
      placeholder: example@host.tld
    validations:
      required: false
  - type: checkbox
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue you agree to follow our [code of conduct](https://github.com/miamatriarx/miamatriarx/code_of_conduct.md) and that any contribution you make will fall under the [MIT](https://github.com/miamatriarx/miamatriarx/license.md) license, in doing so you agree to our terms and void all claims to intellectual propertly or copyright.
      options:
        - label: I agree to your terms and to follow the community's code of conduct.
    validations:
      required: true
