---
name: Code Analysis
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyze
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args:
            -Dsonar.organization=miamatriarx
            -Dsonar.projectKey=miamatriarx_miamatriarx
            -Dsonar.projectBaseDir=.
            -Dsonar.tests=tests
            -Dsonar.verbose=true
