name: CI
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Review
        uses: actions/dependency-review-action@v2
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: github/super-linter@v4
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyze
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args:
            -Dsonar.organization=miamatriarx
            -Dsonar.projectKey=miamatriarx_miamatriarx
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.verbose=true
