---
name: Dependency Analysis
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyze
        uses: actions/dependency-review-action@v2
