---
name: CI
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Test
        run: "echo Success"
